---
- name: 'Wait for JSON RPC port to respond'
  wait_for:
    host: 'localhost'
    port: '{{ erigon_rpc_port }}'
    delay: 20
    connect_timeout: 20
    timeout: 120
    state: drained

- name: 'Query JSON RPC for enode address'
  uri:
    url: http://{{ erigon_rpc_addr }}:{{ erigon_rpc_port }}/
    method: POST
    body: '{"id": 1, "method": "admin_nodeInfo"}'
    body_format: json
    return_content: yes
  register: node_info

- name: 'Save enode address: {{ erigon_enode_file }}'
  copy:
    dest: '{{ erigon_enode_file }}'
    content: '{{ node_info.json.result.enode }}'
    owner: 
    mode: 0644
